version: '3'
services:
#  web:
#    image: nginx
#    ports:
#      - 80:80
#    working_dir: /code
#    volumes:
#      - ../app:/code
#      - ./images/web/logs:/var/logs/nginx
#      - ./images/web/conf.d:/etc/nginx/conf.d
#      - ./../../:/srv/www/
#    depends_on:
#      - fpm

  beta.catalog.fpm:
    build: ./images/php
    volumes:
      - ../app:/code
      - /Users/lilith/.ssh:/root/.ssh
      - ./images/php/conf/php.ini:/usr/local/etc/php/php.ini
    working_dir: /code
    extra_hosts:
      - "ftest-crypto.etp-ets.ru:${CRYPTO_HOST}"
    env_file:
      - .env
#    depends_on:
#      - sphinx
#      - mysql

#  mysql:
#    image: mysql:5.6
#    ports:
#      - 3306:3306
#    environment:
#      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
#      MYSQL_USER: ${MYSQL_USER}
#      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
#      MYSQL_DATABASE: ${MYSQL_DATABASE}
#    volumes:
#      - mysql.data:/var/lib/mysql:rw
#    healthcheck:
#      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
#      timeout: 20s
#      retries: 10

#  sphinx:
#    build: ./images/sphinxsearch/
#    environment:
#      MYSQL_HOST: ${SPHINX_MYSQL_HOST}
#      MYSQL_DATABASE: ${SPHINX_MYSQL_DATABASE}
#      MYSQL_USER: ${SPHINX_MYSQL_USER}
#      MYSQL_PASSWORD: ${SPHINX_MYSQL_PASSWORD}
#    volumes:
#      - sphinx.data:/srv/www/sphinx
#      - ./images/sphinxsearch:/etc/sphinxsearch
#    depends_on:
#      - db

  rabbitmq:
    image: rabbitmq:management
    hostname: sectionks.rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - rabbitmq.data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "node_health_check"]
      interval: 30s
      timeout: 20s
      retries: 10

volumes:
#  sphinx.data:
#  mysql.data:
  rabbitmq.data: