doctrine:
    dbal:
        #url: '%env(resolve:DATABASE_URL)%'
        default_connection:       default
        connections:
            default:
                dbname:           sectionks
                user:             developer
                password:         developer
                host:             10.95.172.72
                server_version:   '5.1'
            catalog_223:
                dbname:           sectionks_catalog_223
                user:             developer
                password:         developer
                host:             10.95.172.72
                server_version:   '5.1'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                mappings:
                    App:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Sectionks'
                        prefix: 'App\Entity\Default'
                        alias: App
#                mappings:
#                    Main:
#                        is_bundle: false
#                        type: annotation
#                        dir: '%kernel.project_dir%/src/Entity/Main'
#                        prefix: 'App\Entity\Main'
#                        alias: Main
            catalog_223:
                connection: catalog_223
#                auto_generate_proxy_classes: true
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
#                auto_mapping: true
                mappings:
                    Catalog:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: Catalog